version: '3'
services:
  pg:
    image: postgres:14.3-alpine3.15
    environment:
    - POSTGRES_PASSWORD=dalongdemo
    ports:
      - 5432:5432
  minio:
    image: minio/minio
    ports:
      - "9002:9000"
      - "19001:19001"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server --console-address :19001 --quiet /data
  dremio:
    build: ./
    image: dalongrong/dremio:21.1-jprofiler
    ports:
      - "9047:9047"
      - "8849:8849"
      - "31010:31010"